name: Build MSAT Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Project
        run: |
          # Melengkapi struktur folder Windows di server
          flutter create --platforms windows .
          
      - name: Download Dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: MSAT-Windows-Xambro
          path: build/windows/x64/runner/Release/
